#!/bin/sh

case "$1" in
	-s)
		pm2 start bash --name oficina-be -- -c "exec php -S 0.0.0.0:8000 -t $HOME/Desktop/Oficina_Lima/api/public"
		wait
		;;
	-t)
		php -S 127.0.0.1:9000 -t api/public &
		PID1=$!

		php -S 127.0.0.1:8000 -t api/public &
		PID2=$!

		echo "9000: $PID1"
		echo "8000: $PID2"
		wait
		;;
	-db)
		echo "Main DB"
		sqlite3 database/database.db < database/database.sql
		;;
	-t)
		./vendor/bin/phpunit tests --display-warnings 
		;;
	*)
		echo "Usage: $0 {-s|-db|-t}"
		exit 1
		;;
esac
